version: "3.4"
services:
  api:
    container_name: API
    build:
      context: .
      target: dev
    ports:
      - "8080:8080"
      - "5858:5858"
    command: yarn dev
    volumes:
      - type: bind
        source: ./src
        target: /app/src
